version: '3.8'

services:
  agai-mcqs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agai_mcqs_masterclass
    ports:
      - "8000:80"
    restart: unless-stopped
